//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace PrazskaLitacka.Webapi.XmlModels {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Stops {
        
        private stopsGroup[] groupField;
        
        private System.DateTime generatedAtField;
        
        private string dataFormatVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("group")]
        public stopsGroup[] group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime generatedAt {
            get {
                return this.generatedAtField;
            }
            set {
                this.generatedAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dataFormatVersion {
            get {
                return this.dataFormatVersionField;
            }
            set {
                this.dataFormatVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class stopsGroup {
        
        private stopsGroupStop[] stopField;
        
        private string nameField;
        
        private string districtCodeField;
        
        private bool isTrainField;
        
        private bool isTrainFieldSpecified;
        
        private int idosCategoryField;
        
        private string idosNameField;
        
        private string fullNameField;
        
        private string uniqueNameField;
        
        private int nodeField;
        
        private int cisField;
        
        private bool cisFieldSpecified;
        
        private float avgLatField;
        
        private float avgLonField;
        
        private float avgJtskXField;
        
        private float avgJtskYField;
        
        private string municipalityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stop")]
        public stopsGroupStop[] stop {
            get {
                return this.stopField;
            }
            set {
                this.stopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string districtCode {
            get {
                return this.districtCodeField;
            }
            set {
                this.districtCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isTrain {
            get {
                return this.isTrainField;
            }
            set {
                this.isTrainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isTrainSpecified {
            get {
                return this.isTrainFieldSpecified;
            }
            set {
                this.isTrainFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int idosCategory {
            get {
                return this.idosCategoryField;
            }
            set {
                this.idosCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string idosName {
            get {
                return this.idosNameField;
            }
            set {
                this.idosNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uniqueName {
            get {
                return this.uniqueNameField;
            }
            set {
                this.uniqueNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int node {
            get {
                return this.nodeField;
            }
            set {
                this.nodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int cis {
            get {
                return this.cisField;
            }
            set {
                this.cisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cisSpecified {
            get {
                return this.cisFieldSpecified;
            }
            set {
                this.cisFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float avgLat {
            get {
                return this.avgLatField;
            }
            set {
                this.avgLatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float avgLon {
            get {
                return this.avgLonField;
            }
            set {
                this.avgLonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float avgJtskX {
            get {
                return this.avgJtskXField;
            }
            set {
                this.avgJtskXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float avgJtskY {
            get {
                return this.avgJtskYField;
            }
            set {
                this.avgJtskYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string municipality {
            get {
                return this.municipalityField;
            }
            set {
                this.municipalityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class stopsGroupStop {
        
        private stopsGroupStopLine[] lineField;
        
        private string idField;
        
        private string platformField;
        
        private string altIdosNameField;
        
        private float latField;
        
        private float lonField;
        
        private float jtskXField;
        
        private float jtskYField;
        
        private string zoneField;
        
        private string gtfsIdsField;
        
        private wheelchairAccessType wheelchairAccessField;
        
        private bool wheelchairAccessFieldSpecified;
        
        private bool isMetroField;
        
        private bool isMetroFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("line")]
        public stopsGroupStopLine[] line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string platform {
            get {
                return this.platformField;
            }
            set {
                this.platformField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string altIdosName {
            get {
                return this.altIdosNameField;
            }
            set {
                this.altIdosNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float lon {
            get {
                return this.lonField;
            }
            set {
                this.lonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float jtskX {
            get {
                return this.jtskXField;
            }
            set {
                this.jtskXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float jtskY {
            get {
                return this.jtskYField;
            }
            set {
                this.jtskYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zone {
            get {
                return this.zoneField;
            }
            set {
                this.zoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string gtfsIds {
            get {
                return this.gtfsIdsField;
            }
            set {
                this.gtfsIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public wheelchairAccessType wheelchairAccess {
            get {
                return this.wheelchairAccessField;
            }
            set {
                this.wheelchairAccessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool wheelchairAccessSpecified {
            get {
                return this.wheelchairAccessFieldSpecified;
            }
            set {
                this.wheelchairAccessFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isMetro {
            get {
                return this.isMetroField;
            }
            set {
                this.isMetroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isMetroSpecified {
            get {
                return this.isMetroFieldSpecified;
            }
            set {
                this.isMetroFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class stopsGroupStopLine {
        
        private int idField;
        
        private string nameField;
        
        private trafficType typeField;
        
        private bool isNightField;
        
        private bool isNightFieldSpecified;
        
        private string directionField;
        
        private string direction2Field;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public trafficType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isNight {
            get {
                return this.isNightField;
            }
            set {
                this.isNightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isNightSpecified {
            get {
                return this.isNightFieldSpecified;
            }
            set {
                this.isNightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string direction2 {
            get {
                return this.direction2Field;
            }
            set {
                this.direction2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum trafficType {
        
        /// <remarks/>
        metro,
        
        /// <remarks/>
        tram,
        
        /// <remarks/>
        train,
        
        /// <remarks/>
        funicular,
        
        /// <remarks/>
        bus,
        
        /// <remarks/>
        ferry,
        
        /// <remarks/>
        trolleybus,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum wheelchairAccessType {
        
        /// <remarks/>
        unknown,
        
        /// <remarks/>
        notPossible,
        
        /// <remarks/>
        possible,
    }
}
